Add&remove
LOctavio/to-do-list pull request #3
Opened 2021-07-24 20:45 UTC by LOctavio

In this milestone, i added functions to add and remove tasks from the to-do list

2021-07-24 21:17 UTC, carlos-ssh requested changes
Hi @LOctavio, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-24 21:17 UTC, carlos-ssh commented on src/index.js
>  const getLocalStorage = () => {
**Kindly solve this issues: **
- I tried to refresh the page and i loose all my tasks in the list. If you check the console in your browser you will find an error related into your line 112.

2021-07-24 21:17 UTC, carlos-ssh commented on src/deleteTasks.js
> +    const { completed } = JSON.parse(localStorage.getItem(localStorage.key(i)));
- After tried to remove complete tasks i have an error. Kindly solve it.

2021-07-25 00:04 UTC, Davidosky007 commented
Hi @LOctavio, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-25 00:23 UTC, merged